### ISSUE TITLE
QuantityMean._reshape

### ISSUE THREAD

**Issue by martinspetlik** [GeoMop/MLMC#145]
`QuantityMean._reshape()`

What is `data`? Rename to something more specific and provide a comment or type hint.
What is the meaning of the`levels` flag? It seems to me that there should possibly be two methods, one calling the other.

**Comment by jbrezmorf** [comment]
We should review whole QuantityMean class and its creation in the `mean_estimate` there are many corner case tests and we should be sure these are neccessary.

**Comment by martinspetlik** [comment]
`QuantityMean._reshape`
 
```
  if isinstance(reshape_shape, int): 
         reshape_shape = [reshape_shape]
```
It is not native numpy behaviour, get rid of that `if`

---
```
 if levels:
      return data.reshape((data.shape[0], *reshape_shape))
```

@jbrezmorf: levels=True should be treated at the calling side, e.g. using a comprehension

**Comment by martinspetlik** [comment]
see #159
