### ISSUE TITLE
replace scalar

### ISSUE THREAD

**Issue by martinspetlik** [GeoMop/MLMC#147]
`QType.replace_scalar`

Think it over again - try to use recursion. 
Note we should be able to replace quantity of `ScalarType` by `ArrayType`, and `ScalarType` doesn't have qtype so we need to create a new `QType` (`ArrayType`).

Suggestions from @jbrezmorf review:
`QType.replace_scalar`

- Convert to proper method of QType.
- This can be much simpler if implemented by recursive construction of the replaced type. Returning the new instance. 
- Use separate implementation for dict and scalar instead of `isinstance`.

`DictType.replace_scalar`

- How is this related to QType.replace_scalar? 
- It is not even a classmethod. It seems to be already in use, but introduction of the probably same static method in QType is confusing.
- Should be probably merged to a single method probably with virtual implementation in some QType subclases.

**Comment by jbrezmorf** [comment]
@martinspetlik replay to the review comment:
I think your suggestion is the same as the previous version (moments_qtype.replace_scalar(moments_array_type)) which is replaced by this staticmethod call.
The main reason of this new implementation is that it allows you to replace scalar quantity by array of scalars which wasn't possible in the previous version.

**Comment by martinspetlik** [comment]
see  #160
