### ISSUE TITLE
Chunk iteration protocol

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/MLMC#152]
Chunk iteration can fully use iteration protocol, yielding the chunk (with level and possibly chunk id and storae specification along the numpy data table), the only parameter of the `samples` then would be `n_samples` possibly given indirectly through the chunk_size.

**Comment by jbrezmorf** [comment]
This affects both `estimate_mean` as well as `hdf5.collected`. Minimal impacto on `Quantity.samples`.

**Comment by martinspetlik** [comment]
Some notes and questions:

- we iterating over the levels, so we should pass `level_id` to `samples()`
- `n_samples` doesn't always have to be specified, sometimes we want to retrieve all collected samples for given `level_id` (e.g. histogram). We can obviously set `n_samples` according to dataset length.
- we should also be able to perform the removal of zeros from the level 0 sample table, that could be done inside `collected()`
- How to set `chunk_size` and other chunk dependent parameters to Storage?
- Does your approach mean one `Storage` instance with one immutable `ChunkSpec`?

- It slightly complicates the implementation of `Storage.sample_pairs()`. We should consider removing this method, it is used by tests only.

**Comment by jbrezmorf** [comment]
Proposed API:

`samples(chunk_size=None, level_id=None, n_samples=None)`

This returns a generator that iterates over given sample subset:
- chunk_size, iterate over samples using at most `chunk_size` samples per chunk
- level_id , if given iterate only over samples of specified level, otherwise iterate over all samples of all levels
- n_samples, if given iterate only over first n_samples, only valid for levle_id == 0

The generator yields the ChunkSpec instance containing:
- level_id
- chunk_id
- data

**Comment by jbrezmorf** [comment]
This leads to passing generator specification through the recursive chain of the `samples` calls down to the storage where the generator is actually created. It would be better to disconnect quantities from the storage. The QuantityStorage would only need the type specification, but can possibly be independent of the storage. Then we can create a chunk generator from the  storage and then pass the generator through the samples calls.

**Comment by jbrezmorf** [comment]
Postpone after resolution the bootstrapping.

**Comment by jbrezmorf** [comment]
Proposed API leads to overcomplicated yielding. Better approach is to
get a ChunkSpec generator from the storage using a method:
```
Storage.chunks(level_id=None, n_samples=None)
```
parameters as in previous proposition of Quantity.samples.

Then pass ChunkSpec to a Quantity.samples method.
QuantityStorage.samples just extract the table from the ChunkSpec.

The main loop then looks like:
```
for chunk in storage.chunks():
    samples = qunatity.samples(chunk)
    ...
```
